[pytest]
env =
    D:PAGERDUTY_API_TOKEN=test
    D:ONCALL_API_TOKEN=test
    D:ONCALL_API_URL=test
    D:MIGRATING_FROM=pagerduty
    D:SPLUNK_API_ID=abcd
    D:SPLUNK_API_KEY=abcd
    D:OPSGENIE_API_KEY=abcd
    D:OPSGENIE_API_URL=test
    D:JIRA_SERVICE_MANAGEMENT_API_KEY=abcd
    D:JIRA_SERVICE_MANAGEMENT_INSTANCE_API_URL=test
    D:JIRA_SERVICE_MANAGEMENT_CLOUD_ID=test
    D:JIRA_SERVICE_MANAGEMENT_ORG_ID=test
